_target_: src.filters.particle.edh_invertible.EDHParticleFlowFilter

n_particles: 2000  # Paper uses 500
n_lambda_steps: 29  # Paper uses 29 exponential steps
filter_type: ekf  # 'ekf' or 'ukf'
resample_threshold: 0.5
